In [3]:
data = open('words_alpha.txt', 'r')
words = data.read().splitlines()

In [4]:
alphabets = set(sorted(list(''.join(words))))

In [5]:
i = 0
stoi = {char : i+1 for i,char in enumerate(sorted(alphabets))}
stoi['.'] = 0

In [6]:
itos = {i:char for char, i in stoi.items()}

In [7]:
import torch

In [8]:
base_matrix = torch.zeros(size=(27,27), dtype=torch.int64)

In [9]:
for word in words:
    word = "." + word+'.'
    for ch1, ch2 in zip(word, word[1:]):
        x_cord, y_cord = stoi[ch1], stoi[ch2]
        base_matrix[x_cord, y_cord] += 1

In [10]:
base_matrix

tensor([[    0, 25417, 18413, 32107, 18733, 14197, 11893, 10953, 13743, 13199,
          2840,  3952, 10002, 19805, 13459, 12681, 34860,  1793, 16783, 38764,
         18819, 22767,  5329,  6559,   507,  1143,  1387],
        [16373,   255, 13238, 18022,  9605,  6131,  2147,  8545,  1449,  6588,
           318,  3053, 40559, 11453, 40043,   389, 10562,   341, 31754, 16637,
         42056,  5457,  3495,  1952,  1286,  2611,  1474],
        [  638,  8685,  1711,   390,   452,  8859,   144,    87,   187,  8912,
           256,    36, 12412,   237,   166,  6967,   206,    10,  6095,  1525,
           492,  4645,   141,    78,     4,   596,    10],
        [13690, 23273,    23,  2385,    53, 14903,    19,    14, 19822, 11481,
             0,  6525,  5088,    52,   228, 24157,    42,   178,  8336,  1031,
         10302,  7752,     2,    20,     1,  3559,    45],
        [30894,  8639,   358,   201,  1822, 22148,   343,  1029,   479, 19349,
           294,    46,  3017,   619,  1424,  8317,   

In [11]:
total_per_row = torch.sum(input=base_matrix,dim=1, keepdim= True, dtype=torch.int64)

In [12]:
# total_per_row

In [13]:
# prob & sum successfully equal to zero
# print(torch.sum(input=(base_matrix / total_per_row), keepdim=True, dim=1))
probs = base_matrix / total_per_row
#probs

In [14]:
word = []
current_index = 0
for i in range(100000):
    while True:
        row = probs[current_index]
        sampled_tensor = torch.multinomial(row, num_samples=1).item()
        word += itos[sampled_tensor]
        if sampled_tensor == 0:
            break
        current_index = sampled_tensor
    # limiter that only prints words between 3 and 6 characters long
    if len(word) >= 3 and len(word) <= 6:
        print("".join(word))
    word = []
    current_index = 0

chur.
ky.
ssco.
fishy.
pph.
peal.
pry.
orel.
de.
dit.
toh.
wati.
mil.
uica.
ales.
stha.
sy.
cagy.
tis.
uns.
prses.
im.
en.
ps.
jos.
selie.
fu.
praf.
uron.
iggh.
utrth.
uroc.
niox.
dan.
ecyan.
cenek.
pss.
soily.
dy.
pese.
tes.
meaik.
gne.
stis.
taly.
rly.
st.
pa.
bo.
shica.
min.
prnot.
me.
pedy.
urm.
ul.
cam.
aiee.
utere.
usind.
re.
kabr.
ut.
er.
do.
ca.
ut.
ene.
gl.
fem.
qun.
bin.
dge.
ke.
nspbe.
sc.
he.
pales.
urm.
funyn.
ed.
luver.
ugge.
pedes.
pten.
toges.
th.
hoo.
tes.
uper.
teer.
kl.
gis.
hari.
ksidy.
gele.
acog.
codgr.
cy.
sslin.
in.
py.
ire.
ade.
cis.
na.
lus.
wog.
rit.
deteg.
pr.
est.
anind.
ns.
cho.
ay.
ive.
ulod.
fy.
ess.
is.
mece.
leem.
gn.
igums.
tha.
shy.
bateh.
ful.
ure.
ivis.
drprs.
fus.
hy.
als.
ilan.
acrin.
rnd.
dec.
sts.
ca.
patia.
od.
nod.
ul.
dom.
alcy.
ps.
bl.
st.
ffize.
congy.
guic.
strpy.
mes.
sus.
ss.
hor.
daky.
les.
cox.
wis.
atid.
sl.
se.
bal.
anist.
bltan.
phe.
en.
sul.
bonas.
ly.
id.
sste.
frm.
palun.
raint.
dyrng.
ront.
ly.
beng.
orpi.
innas.
wr.
pra.
bins.

In [15]:
x_piles = []
y_piles = []

for word in words:
    word = "." + word + "."
    for ch1, ch2 in zip(word, word[1:]):
        x_piles.append(stoi[ch1])
        y_piles.append(stoi[ch2])

# Convert them into raw PyTorch Tensors
X = torch.tensor(x_piles)
Y = torch.tensor(y_piles)

In [16]:
X_enc = torch.nn.functional.one_hot(X, num_classes=27).float()
X_enc.shape

torch.Size([3864812, 27])

In [17]:
W = torch.randn(size=(27,27), dtype=torch.float32, requires_grad=True)

In [18]:

logits = X_enc @ W
logits.shape

torch.Size([3864812, 27])

In [19]:
counts = logits.exp()
counts

tensor([[ 0.4682,  5.2937,  3.7963,  ...,  0.6873,  1.0494,  1.7027],
        [ 4.4198,  1.7058, 10.1650,  ...,  1.1324,  2.0052,  0.2522],
        [ 0.4682,  5.2937,  3.7963,  ...,  0.6873,  1.0494,  1.7027],
        ...,
        [ 6.0022,  1.8745,  2.8758,  ...,  4.6752,  0.6029,  0.1986],
        [ 1.0169,  3.1785,  1.1112,  ...,  6.6614,  0.7966,  1.8687],
        [ 0.5101,  1.6278,  0.7647,  ...,  0.1202,  0.4142,  0.5141]],
       grad_fn=<ExpBackward0>)

In [20]:
probs_nn = counts / counts.sum(dim = 1, keepdim=True)
probs_nn

tensor([[0.0129, 0.1463, 0.1049,  ..., 0.0190, 0.0290, 0.0470],
        [0.0749, 0.0289, 0.1724,  ..., 0.0192, 0.0340, 0.0043],
        [0.0129, 0.1463, 0.1049,  ..., 0.0190, 0.0290, 0.0470],
        ...,
        [0.0948, 0.0296, 0.0454,  ..., 0.0739, 0.0095, 0.0031],
        [0.0183, 0.0571, 0.0200,  ..., 0.1197, 0.0143, 0.0336],
        [0.0144, 0.0460, 0.0216,  ..., 0.0034, 0.0117, 0.0145]],
       grad_fn=<DivBackward0>)

In [21]:
probs_nn[0].sum()

tensor(1., grad_fn=<SumBackward0>)

In [22]:
correct_probs = probs_nn[torch.arange(3864812), Y]
loss = (-correct_probs.log().mean())
loss.item()

3.840240955352783

In [23]:
W = torch.randn(size=(27,27), dtype=torch.float32, requires_grad=True)
for i in range(100):
    logits = X_enc @ W
    counts = logits.exp()
    probs_nn = counts / counts.sum(dim = 1, keepdim=True)

    correct_probs = probs_nn[torch.arange(3864812), Y]
    loss = -correct_probs.log().mean()

    loss.backward()

    with torch.no_grad():
        W -= 10 * W.grad
    W.grad.zero_()
    print(f'{loss=}')

loss=tensor(3.7963, grad_fn=<NegBackward0>)
loss=tensor(3.7299, grad_fn=<NegBackward0>)
loss=tensor(3.6689, grad_fn=<NegBackward0>)
loss=tensor(3.6125, grad_fn=<NegBackward0>)
loss=tensor(3.5603, grad_fn=<NegBackward0>)
loss=tensor(3.5117, grad_fn=<NegBackward0>)
loss=tensor(3.4664, grad_fn=<NegBackward0>)
loss=tensor(3.4241, grad_fn=<NegBackward0>)
loss=tensor(3.3845, grad_fn=<NegBackward0>)
loss=tensor(3.3475, grad_fn=<NegBackward0>)
loss=tensor(3.3127, grad_fn=<NegBackward0>)
loss=tensor(3.2801, grad_fn=<NegBackward0>)
loss=tensor(3.2494, grad_fn=<NegBackward0>)
loss=tensor(3.2205, grad_fn=<NegBackward0>)
loss=tensor(3.1932, grad_fn=<NegBackward0>)
loss=tensor(3.1674, grad_fn=<NegBackward0>)
loss=tensor(3.1431, grad_fn=<NegBackward0>)
loss=tensor(3.1201, grad_fn=<NegBackward0>)
loss=tensor(3.0983, grad_fn=<NegBackward0>)
loss=tensor(3.0776, grad_fn=<NegBackward0>)
loss=tensor(3.0581, grad_fn=<NegBackward0>)
loss=tensor(3.0396, grad_fn=<NegBackward0>)
loss=tensor(3.0220, grad_fn=<Neg

In [26]:
with torch.no_grad():
    for _ in range(20):
        word = []
        current_index = 0
        while True:
            x = torch.nn.functional.one_hot(torch.tensor([current_index]), num_classes=27).float()
            logits = x @ W
            probs = logits.softmax(dim=1)[0]
            sampled_tensor = torch.multinomial(probs, num_samples=1).item()
            if sampled_tensor == 0:
                break
            word.append(itos[sampled_tensor])
            current_index = sampled_tensor
        if len(word) >= 3:
            print("".join(word))

gceerercfs
wiled
atin
bosingrs
toiiopra
siswcaraphoneks
uqhnevpgcit
abbcobfinxg
tomrchkitrcrinbfijvon
lfbz
erenkgrtinhppensphzbleales
ingentohhichbgwinndtrzuame
hunc
groeg
cbigy
ftiurshet
prlac
